spring.application.name=Antss_Prescription

spring.datasource.url=jdbc:postgresql://ep-square-lab-aptqujrx-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kTj0hXfNHne8
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=RishBootDevAntssPrescription2374646383937836723748474
app.jwt.access-token-expiration=3600000
app.jwt.refresh-token-expiration=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=antss9755@gmail.com
spring.mail.password=hglc qcdm umli yoza

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.admin.email=rishbootdev@gmail.com
app.admin.default-password=Admin@123

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=2030
app.base-url=http://localhost:2030
